### PR TITLE
Fixes #3: Add support for applying XSLT transformations to the XML report generated by checkstyle

### LINKED ISSUE #3: New Feature: support for generating a XLST formatted report
At the moment, the plugin does not support formatting of the XML report by using an XLST style sheet. Would it be possible to add this feature? (Reading the XML itself isn't as easy as reading a formatted version.) I believe that checkstyle itself includes style files that could be used.

### PR DESCRIPTION
**Pull request by ajsquared**

### CODE REVIEW

**Comment by ajsquared** [comment]
@andrewdbate Does this look like it will meet your needs?

**Comment by andrewdbate** [comment]
This looks great!

One minor comment: In the `checkstyle-noframes.xml` file, there is the line
`Designed for use with <a href='http://checkstyle.sourceforge.net/'>CheckStyle</a> and <a href='http://jakarta.apache.org'>Ant</a>.</td>`. Do you want to change/remove the reference to Ant?

**Comment by ajsquared** [comment]
@andrewdbate Good call, I'll take that out.

Travis is't cooperating with the test I wrote for this, but once that's fixed I'll publish a new version with this feature.

**Comment by ajsquared** [comment]
Merged at 52cf49118ebf642f10a0d7666436e65c18bd5931

**Pull request closed without merging**
