### PR TITLE
Updated to latest checkstyle released released 01/31/2016

### PR DESCRIPTION
**Pull request by AlejandroRivera**

### CODE REVIEW

**Comment by ajsquared** [comment]
Thanks for this.

I'm thinking we can set the version to `6.+` to have it automatically pull down the newest release in the 6.x series (per http://ant.apache.org/ivy/history/2.3.0/ivyfile/dependency.html#revision).

**Comment by ajsquared** [comment]
I will publish a new release today with this change in it.

**Comment by AlejandroRivera** [comment]
> I'm thinking we can set the version to 6.+ to have it automatically pull down the newest release in the 6.x series (per http://ant.apache.org/ivy/history/2.3.0/ivyfile/dependency.html#revision).

sounds tempting, but i'd be a bit worried about the implications of not having consistent builds if a new version of checkstyle gets released that breaks my build when a previous one didn't. 

> I will publish a new release today with this change in it.

sounds good :+1:

**Comment by ajsquared** [comment]
I've just published version 2.1.0 with this change in it.

**Pull request merged**
