### PR TITLE
Cross build plugin for SBT 0.13.x & 1.0.x

### PR DESCRIPTION
**Pull request by stringbean**
Includes:

* Update project SBT to 0.13.16.
* Fix deprecated syntax in project & scripted tests.
* Add cross build settings for 0.13.16 & 1.0.1

### CODE REVIEW

**Comment by dossett** [comment]
Thank you @stringbean!  I'll check this out soon.

**Comment by lhohan** [comment]
Looking to move to sbt 1.0.1 and using this plugin. 
So +1 on PR

**Comment by stringbean** [comment]
@dossett any progress on this?

**Comment by dossett** [comment]
HI @stringbean I'm on new parent leave right now, so not yet.  Once my home situation is a bit more stable, this is at the top of my to do list of fun side projects while I'm on leave.

**Comment by rmcloughlin** [comment]
This would be great to have.

**Comment by dvirf1** [comment]
@dossett I noticed in your overview tab that you're back in business :) maybe now it's the time to merge

**Comment by dossett** [comment]
Thanks for the reminder @dvirf1 !  I will look this week.

**Comment by dossett** [comment]
Thanks @stringbean, I'll be releasing 3.1.0 soon

**Comment by dossett** [comment]
I got some errors in the publish process, but it appears to be out:
https://oss.sonatype.org/content/repositories/public/com/etsy/sbt-checkstyle-plugin_2.12_1.0/
https://oss.sonatype.org/content/repositories/public/com/etsy/sbt-checkstyle-plugin_2.10_0.13/

If anyone has issues adding those versions, please open an issue. Thanks to everyone who commented/contributed on this PR.

**Pull request merged**
